# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios_apikit_codable_sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_apikit_codable_sample
  plugin 'cocoapods-keys', {
  :project => "ios_apikit_codable_sample",
  :keys => [
    "accessKey"
]}

  target 'ios_apikit_codable_sampleTests' do
    inherit! :search_paths
    # Pods for testing
    plugin 'cocoapods-keys', {
      :project => "ios_apikit_codable_sampleTests",
      :keys => [
        "accessKey"
    ]}
  end

end
